version: "3.9"

services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
        
  backend:
    depends_on:
      - db
    build: ./notification_bot_backend/
    container_name: nb_backend
    ports:
      - "8001:8001"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: "5432"
      TELEGRAM_SENDER_HOST: sender
      TELEGRAM_SENDER_PORT: "8002" 
      API_TOKEN: ${API_TOKEN}
    env_file:
      - .env

  telegram_client:
    depends_on:
      - backend
    build: ./notification_bot_telegram_client/
    container_name: nb_telegram_client
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8001
      API_TOKEN: ${API_TOKEN}
    env_file:
      - .env

  sender:
    depends_on:
      - backend
    build: ./notification_bot_sender/
    container_name: nb_sender
    ports:
      - "8002:8002"
    environment:
      API_TOKEN: ${API_TOKEN}
    env_file:
      - .env

